### ISSUE TITLE
登陆后错误

### ISSUE THREAD

**Issue by smg123233** [thggdx/NeteaseMusicDownload#1]
[2023-08-30 10:12:59,834][INFO] : 当前工作路径: C:\Users\31046\Desktop\NeteaseMusicDownload-main
[2023-08-30 10:13:02,141][INFO] : API地址: https://ncm-api.thggdx.eu.org
[2023-08-30 10:13:03,924][INFO] : 未登录
[2023-08-30 10:13:14,539][INFO] : 登陆方式: 手机验证码登陆
[2023-08-30 10:13:25,727][ERROR] : An error occurred: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\31046\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31046\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31046\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31046\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\31046\Desktop\NeteaseMusicDownload-main\main.py", line 206, in <module>
    main()
  File "C:\Users\31046\Desktop\NeteaseMusicDownload-main\main.py", line 116, in main
    data=API.captchaLogin(phone,captcha,ctcode,api)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31046\Desktop\NeteaseMusicDownload-main\API.py", line 123, in captchaLogin
    data=requests.post(url,data=data).json()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31046\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2023-08-30 10:13:25,730][ERROR] : 程序异常退出

**Comment by thggdx** [comment]
默认的api是部署在vercel上的，有很多人使用可能被风控无法用于登录，建议自行部署api，我用自己部署的api测试过是能正常登录的
